definitions:
  memo:
    x-go-type: "github/podhmo/swagger2go/person.Memo"
    type: object
    properties:
      name:
        type: string
  memo2:
    x-go-type: "github/podhmo/another.Memo"
    type: object
    properties:
      name:
        type: string
  people:
    type: array
    items:
      $ref: "#/definitions/person"
  person:
    type: object
    properties:
      name:
        type: string
      age:
        type: integer
      memo:
        $ref: "#/definitions/memo"
      memo2:
        $ref: "#/definitions/memo2"
      father:
        $ref: "#/definitions/person"
      mother:
        $ref: "#/definitions/person"
  person2:
    type: object
    properties:
      name:
        type: string
      age:
        type: integer
      memo:
        $ref: "#/definitions/memo"
      memo2:
        $ref: "#/definitions/memo2"
      father:
        $ref: "#/definitions/person2"
      mother:
        $ref: "#/definitions/person2"
  people2:
    type: array
    items:
      $ref: "#/definitions/person2"
